import type { Candidate } from '@/types';

export const mockCandidates: Candidate[] = [
  {
    id: '1',
    name: 'Sarah Chen',
    title: 'Senior Full Stack Developer',
    location: 'San Francisco, CA',
    avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=400',
    skills: ['React', 'Node.js', 'TypeScript', 'Python', 'AWS'],
    experience: 6,
    matchScore: 95,
    matchDescription: 'Excellent match with strong full-stack experience and leadership skills. Has worked on similar projects in the fintech space.',
    email: 'sarah.chen@email.com',
    phone: '+1 (555) 123-4567',
    linkedin: 'https://linkedin.com/in/sarahchen',
    summary:
      'Passionate full-stack developer with 6+ years of experience building scalable web applications. Expertise in modern JavaScript frameworks and cloud technologies.',
    previousRoles: [
      {
        company: 'TechFlow Inc.',
        position: 'Senior Software Engineer',
        duration: '2021 - Present',
        description: 'Led development of customer-facing applications serving 100K+ users. Architected microservices infrastructure on AWS.',
      },
      {
        company: 'StartupXYZ',
        position: 'Full Stack Developer',
        duration: '2019 - 2021',
        description: 'Built MVP from scratch using React and Node.js. Collaborated closely with design and product teams.',
      },
    ],
    education: [
      {
        institution: 'Stanford University',
        degree: 'B.S. Computer Science',
        year: '2018',
      },
    ],
  },
  {
    id: '2',
    name: 'Marcus Rodriguez',
    title: 'DevOps Engineer',
    location: 'Austin, TX',
    avatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=400',
    skills: ['Docker', 'Kubernetes', 'AWS', 'Terraform', 'Jenkins'],
    experience: 8,
    matchScore: 88,
    matchDescription: 'Strong DevOps background with extensive cloud infrastructure experience. Perfect for scaling applications.',
    email: 'marcus.rodriguez@email.com',
    phone: '+1 (555) 234-5678',
    linkedin: 'https://linkedin.com/in/marcusrodriguez',
    summary: 'DevOps engineer specializing in cloud infrastructure and CI/CD automation. Proven track record of reducing deployment times by 70%.',
    previousRoles: [
      {
        company: 'CloudTech Solutions',
        position: 'Senior DevOps Engineer',
        duration: '2020 - Present',
        description: 'Managed infrastructure for 50+ microservices. Implemented automated deployment pipelines.',
      },
    ],
    education: [
      {
        institution: 'University of Texas at Austin',
        degree: 'B.S. Computer Engineering',
        year: '2016',
      },
    ],
  },
  {
    id: '3',
    name: 'Emily Johnson',
    title: 'UX/UI Designer',
    location: 'New York, NY',
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=400',
    skills: ['Figma', 'Adobe Creative Suite', 'Prototyping', 'User Research', 'Design Systems'],
    experience: 5,
    matchScore: 82,
    matchDescription: 'Creative designer with strong user research background. Great for improving user experience.',
    email: 'emily.johnson@email.com',
    phone: '+1 (555) 345-6789',
    linkedin: 'https://linkedin.com/in/emilyjohnson',
    summary: 'UX/UI designer passionate about creating intuitive digital experiences. Expert in design systems and user-centered design.',
    previousRoles: [
      {
        company: 'Design Studio NYC',
        position: 'Senior UX Designer',
        duration: '2022 - Present',
        description: 'Led design for mobile apps with 1M+ downloads. Conducted user research and usability testing.',
      },
    ],
    education: [
      {
        institution: 'Parsons School of Design',
        degree: 'B.F.A. Communication Design',
        year: '2019',
      },
    ],
  },
  {
    id: '4',
    name: 'David Kim',
    title: 'Data Scientist',
    location: 'Seattle, WA',
    avatar: 'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=400',
    skills: ['Python', 'Machine Learning', 'SQL', 'TensorFlow', 'R'],
    experience: 4,
    matchScore: 78,
    matchDescription: 'Data science expertise with machine learning focus. Good fit for analytics-heavy projects.',
    email: 'david.kim@email.com',
    phone: '+1 (555) 456-7890',
    linkedin: 'https://linkedin.com/in/davidkim',
    summary: 'Data scientist with expertise in machine learning and statistical analysis. Experienced in building predictive models.',
    previousRoles: [
      {
        company: 'Analytics Corp',
        position: 'Data Scientist',
        duration: '2021 - Present',
        description: 'Built ML models for customer segmentation and churn prediction. Improved model accuracy by 25%.',
      },
    ],
    education: [
      {
        institution: 'University of Washington',
        degree: 'M.S. Data Science',
        year: '2021',
      },
    ],
  },
  {
    id: '5',
    name: 'Lisa Zhang',
    title: 'Product Manager',
    location: 'Los Angeles, CA',
    avatar: 'https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?auto=compress&cs=tinysrgb&w=400',
    skills: ['Product Strategy', 'Agile', 'Analytics', 'User Research', 'Roadmapping'],
    experience: 7,
    matchScore: 85,
    matchDescription: 'Experienced product manager with strong analytical skills. Great for leading product initiatives.',
    email: 'lisa.zhang@email.com',
    phone: '+1 (555) 567-8901',
    linkedin: 'https://linkedin.com/in/lisazhang',
    summary: 'Product manager with 7+ years of experience launching successful products. Expert in data-driven decision making.',
    previousRoles: [
      {
        company: 'ProductTech Inc.',
        position: 'Senior Product Manager',
        duration: '2020 - Present',
        description: 'Led product strategy for B2B SaaS platform. Increased user engagement by 40%.',
      },
    ],
    education: [
      {
        institution: 'UCLA Anderson',
        degree: 'MBA',
        year: '2017',
      },
    ],
  },
  {
    id: '6',
    name: 'Alex Thompson',
    title: 'Mobile Developer',
    location: 'Miami, FL',
    avatar: 'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=400',
    skills: ['React Native', 'Swift', 'Kotlin', 'Flutter', 'iOS'],
    experience: 5,
    matchScore: 80,
    matchDescription: 'Mobile development specialist with cross-platform expertise. Perfect for mobile-first projects.',
    email: 'alex.thompson@email.com',
    phone: '+1 (555) 678-9012',
    linkedin: 'https://linkedin.com/in/alexthompson',
    summary: 'Mobile developer specializing in cross-platform applications. Built apps with millions of downloads.',
    previousRoles: [
      {
        company: 'Mobile Solutions LLC',
        position: 'Senior Mobile Developer',
        duration: '2021 - Present',
        description: 'Developed iOS and Android apps for various industries. Led mobile team of 5 developers.',
      },
    ],
    education: [
      {
        institution: 'Florida Institute of Technology',
        degree: 'B.S. Software Engineering',
        year: '2019',
      },
    ],
  },
];
