/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admin: AdminAuthOperations;
  };
  blocks: {};
  collections: {
    company: Company;
    grade: Grade;
    permission: Permission;
    project: Project;
    location: Location;
    offerStatus: OfferStatus;
    offer: Offer;
    service: Service;
    skill: Skill;
    role: Role;
    user: User;
    media: Media;
    specialist: Specialist;
    specialization: Specialization;
    city: City;
    country: Country;
    businessArea: BusinessArea;
    post: Post;
    job: Job;
    admin: Admin;
    assistant: Assistant;
    message: Message;
    industry: Industry;
    language: Language;
    seed: Seed;
    category: Category;
    embedding: Embedding;
    dataSource: DataSource;
    event: Event;
    log: Log;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    company: CompanySelect<false> | CompanySelect<true>;
    grade: GradeSelect<false> | GradeSelect<true>;
    permission: PermissionSelect<false> | PermissionSelect<true>;
    project: ProjectSelect<false> | ProjectSelect<true>;
    location: LocationSelect<false> | LocationSelect<true>;
    offerStatus: OfferStatusSelect<false> | OfferStatusSelect<true>;
    offer: OfferSelect<false> | OfferSelect<true>;
    service: ServiceSelect<false> | ServiceSelect<true>;
    skill: SkillSelect<false> | SkillSelect<true>;
    role: RoleSelect<false> | RoleSelect<true>;
    user: UserSelect<false> | UserSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    specialist: SpecialistSelect<false> | SpecialistSelect<true>;
    specialization: SpecializationSelect<false> | SpecializationSelect<true>;
    city: CitySelect<false> | CitySelect<true>;
    country: CountrySelect<false> | CountrySelect<true>;
    businessArea: BusinessAreaSelect<false> | BusinessAreaSelect<true>;
    post: PostSelect<false> | PostSelect<true>;
    job: JobSelect<false> | JobSelect<true>;
    admin: AdminSelect<false> | AdminSelect<true>;
    assistant: AssistantSelect<false> | AssistantSelect<true>;
    message: MessageSelect<false> | MessageSelect<true>;
    industry: IndustrySelect<false> | IndustrySelect<true>;
    language: LanguageSelect<false> | LanguageSelect<true>;
    seed: SeedSelect<false> | SeedSelect<true>;
    category: CategorySelect<false> | CategorySelect<true>;
    embedding: EmbeddingSelect<false> | EmbeddingSelect<true>;
    dataSource: DataSourceSelect<false> | DataSourceSelect<true>;
    event: EventSelect<false> | EventSelect<true>;
    log: LogSelect<false> | LogSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'ru';
  user: Admin & {
    collection: 'admin';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company".
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service".
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grade".
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permission".
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project".
 */
export interface Project {
  id: string;
  top?: boolean | null;
  mainPhoto?: (string | null) | Media;
  gallery?:
    | {
        photo?: (string | Media)[] | null;
        id?: string | null;
      }[]
    | null;
  name: string;
  header: string;
  aboutTeam?: string | null;
  stack: (string | Skill)[];
  about: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  about_html?: string | null;
  year?: string | null;
  term?: number | null;
  budget?: number | null;
  specialists?:
    | {
        specialist?: (string | null) | Specialist;
        grade?: (string | null) | Grade;
        specialization?: (string | Specialization)[] | null;
        id?: string | null;
      }[]
    | null;
  businessArea: string | BusinessArea;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill".
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specialist".
 */
export interface Specialist {
  id: string;
  user?: (string | null) | User;
  externalId?: string | null;
  title?: string | null;
  name?: string | null;
  top?: boolean | null;
  firstName?: string | null;
  lastName?: string | null;
  middleName?: string | null;
  birthDate?: string | null;
  experience?:
    | {
        name?: string | null;
        start?: string | null;
        end?: string | null;
        untilNow?: boolean | null;
        company?: string | null;
        position?: string | null;
        industry?: (string | null) | Industry;
        description?: string | null;
        aboutTeam?: string | null;
        achievements?: string | null;
        stack?: (string | Skill)[] | null;
        id?: string | null;
      }[]
    | null;
  workFormat?: ('remote' | 'office' | 'mixed') | null;
  employmentType?: ('full' | 'short') | null;
  additionalEducations?:
    | {
        name?: string | null;
        year?: number | null;
        file?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  educations?:
    | {
        name?: string | null;
        level: 'secondaryGeneral' | 'CandidateOfSciences' | 'masterOfScience' | 'higher' | 'unfinishedHigher' | 'secondary' | 'other';
        major?: string | null;
        year?: number | null;
        id?: string | null;
      }[]
    | null;
  salary?: {
    amount?: number | null;
    currency?: ('RUB' | 'EUR' | 'USD') | null;
    hourlyRate?: number | null;
  };
  contacts?: {
    phone?: string | null;
    email?: string | null;
    telegram?: string | null;
    other?: string | null;
  };
  language?:
    | {
        language?: (string | null) | Language;
        level?: ('A1' | 'A2' | 'B1' | 'B2' | 'C1' | 'C2' | 'L1' | '-') | null;
        id?: string | null;
      }[]
    | null;
  availableFrom?: string | null;
  employment?: ('full' | 'part' | 'project' | 'probation') | null;
  relocation?: ('noRelocation' | 'relocation' | 'relocationDesirable') | null;
  schedule?: ('remote' | 'shiftWork' | 'full' | 'flexible') | null;
  hasVehicle?: boolean | null;
  driveExperience?: string | null;
  businessTripReadiness?: ('never' | 'ready' | 'sometimes') | null;
  foreignProjectsReadiness?: ('yes' | 'no') | null;
  age?: number | null;
  status?: ('created' | 'archive') | null;
  citizenship?:
    | {
        name: string | Country;
        id?: string | null;
      }[]
    | null;
  jobSearchStatus?: ('active' | 'open' | 'notLooking') | null;
  driverLicenseTypes?:
    | {
        type: string;
        id?: string | null;
      }[]
    | null;
  travelTime?: ('any' | 'lessThanHour' | 'fromHourToOneAndHalf') | null;
  aboutMe?: string | null;
  gender?: ('female' | 'male') | null;
  img?: (string | null) | Media;
  skills?: (string | Skill)[] | null;
  company?: (string | null) | Company;
  grade?: (string | null) | Grade;
  specialization?: (string | null) | Specialization;
  city?: (string | null) | City;
  country?: (string | null) | Country;
  services?: (string | Service)[] | null;
  visibility?: ('visible' | 'hidden') | null;
  skillsExtracted?: boolean | null;
  formattedExperienceSkills?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  dataSource?: (string | null) | DataSource;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user".
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "role".
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industry".
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "language".
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "country".
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specialization".
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "category".
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "city".
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dataSource".
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "businessArea".
 */
export interface BusinessArea {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "location".
 */
export interface Location {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offerStatus".
 */
export interface OfferStatus {
  id: string;
  name: string;
  code: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offer".
 */
export interface Offer {
  id: string;
  specialist: string | Specialist;
  job: string | Job;
  agent?: (string | null) | User;
  rate?: number | null;
  requirements?:
    | {
        requirement: string;
        mandatory?: boolean | null;
        matched: number;
        comment?: string | null;
        questions?:
          | {
              question?: string | null;
              answer?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  status: string | OfferStatus;
  salary?: {
    amount?: number | null;
    currency?: ('RUB' | 'EUR' | 'USD') | null;
    hourlyRate?: number | null;
  };
  matched?: number | null;
  comment?: string | null;
  assessmentOfRequirements?: string | null;
  createdBy?: ('user' | 'databaseСomparison' | 'loader' | 'cosineSimilarity' | 'importByLink') | null;
  respondedAt?: string | null;
  matchedBatch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job".
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post".
 */
export interface Post {
  id: string;
  image?: (string | null) | Media;
  title: string;
  description?: string | null;
  text: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  text_html?: string | null;
  date?: string | null;
  author: string | User;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin".
 */
export interface Admin {
  id: string;
  roles?: 'admin'[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assistant".
 */
export interface Assistant {
  id: string;
  name?: string | null;
  isDeleted?: boolean | null;
  user?: (string | null) | User;
  guestToken?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "message".
 */
export interface Message {
  id: string;
  content?: string | null;
  media?: (string | Media)[] | null;
  assistant: string | Assistant;
  user?: (string | null) | User;
  status?: ('created' | 'processing' | 'success' | 'error') | null;
  role?: ('user' | 'assistant') | null;
  inputTokens?: number | null;
  outputTokens?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seed".
 */
export interface Seed {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "embedding".
 */
export interface Embedding {
  id: string;
  query?: string | null;
  tableName?: string | null;
  embeddingId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event".
 */
export interface Event {
  id: string;
  name: string;
  description?: string | null;
  date: string;
  startTime: string;
  endTime?: string | null;
  calendarId: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "log".
 */
export interface Log {
  id: string;
  name?: string | null;
  type?: ('info' | 'error') | null;
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  messageType?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'company';
        value: string | Company;
      } | null)
    | ({
        relationTo: 'grade';
        value: string | Grade;
      } | null)
    | ({
        relationTo: 'permission';
        value: string | Permission;
      } | null)
    | ({
        relationTo: 'project';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'location';
        value: string | Location;
      } | null)
    | ({
        relationTo: 'offerStatus';
        value: string | OfferStatus;
      } | null)
    | ({
        relationTo: 'offer';
        value: string | Offer;
      } | null)
    | ({
        relationTo: 'service';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'skill';
        value: string | Skill;
      } | null)
    | ({
        relationTo: 'role';
        value: string | Role;
      } | null)
    | ({
        relationTo: 'user';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'specialist';
        value: string | Specialist;
      } | null)
    | ({
        relationTo: 'specialization';
        value: string | Specialization;
      } | null)
    | ({
        relationTo: 'city';
        value: string | City;
      } | null)
    | ({
        relationTo: 'country';
        value: string | Country;
      } | null)
    | ({
        relationTo: 'businessArea';
        value: string | BusinessArea;
      } | null)
    | ({
        relationTo: 'post';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'job';
        value: string | Job;
      } | null)
    | ({
        relationTo: 'admin';
        value: string | Admin;
      } | null)
    | ({
        relationTo: 'assistant';
        value: string | Assistant;
      } | null)
    | ({
        relationTo: 'message';
        value: string | Message;
      } | null)
    | ({
        relationTo: 'industry';
        value: string | Industry;
      } | null)
    | ({
        relationTo: 'language';
        value: string | Language;
      } | null)
    | ({
        relationTo: 'seed';
        value: string | Seed;
      } | null)
    | ({
        relationTo: 'category';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'embedding';
        value: string | Embedding;
      } | null)
    | ({
        relationTo: 'dataSource';
        value: string | DataSource;
      } | null)
    | ({
        relationTo: 'event';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'log';
        value: string | Log;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'admin';
    value: string | Admin;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'admin';
    value: string | Admin;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company_select".
 */
export interface CompanySelect<T extends boolean = true> {
  name?: T;
  inn?: T;
  entityType?: T;
  entityRole?: T;
  data?:
    | T
    | {
        ogrn?: T;
        kpp?: T;
        okved?: T;
        regDate?: T;
        regAddress?: T;
        factAddress?: T;
        director?: T;
        taxForm?: T;
        bik?: T;
        bankName?: T;
        accountNumber?: T;
      };
  services?: T;
  dossier?:
    | T
    | {
        code?: T;
        content?: T;
        id?: T;
      };
  telegramChatId?: T;
  telegramChatNotificationId?: T;
  isSpecialistNotificationSub?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grade_select".
 */
export interface GradeSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permission_select".
 */
export interface PermissionSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project_select".
 */
export interface ProjectSelect<T extends boolean = true> {
  top?: T;
  mainPhoto?: T;
  gallery?:
    | T
    | {
        photo?: T;
        id?: T;
      };
  name?: T;
  header?: T;
  aboutTeam?: T;
  stack?: T;
  about?: T;
  about_html?: T;
  year?: T;
  term?: T;
  budget?: T;
  specialists?:
    | T
    | {
        specialist?: T;
        grade?: T;
        specialization?: T;
        id?: T;
      };
  businessArea?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "location_select".
 */
export interface LocationSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offerStatus_select".
 */
export interface OfferStatusSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offer_select".
 */
export interface OfferSelect<T extends boolean = true> {
  specialist?: T;
  job?: T;
  agent?: T;
  rate?: T;
  requirements?:
    | T
    | {
        requirement?: T;
        mandatory?: T;
        matched?: T;
        comment?: T;
        questions?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
        id?: T;
      };
  status?: T;
  salary?:
    | T
    | {
        amount?: T;
        currency?: T;
        hourlyRate?: T;
      };
  matched?: T;
  comment?: T;
  assessmentOfRequirements?: T;
  createdBy?: T;
  respondedAt?: T;
  matchedBatch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service_select".
 */
export interface ServiceSelect<T extends boolean = true> {
  top?: T;
  name?: T;
  content?: T;
  content_html?: T;
  gallery?:
    | T
    | {
        photo?: T;
        id?: T;
      };
  amount?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill_select".
 */
export interface SkillSelect<T extends boolean = true> {
  name?: T;
  parent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "role_select".
 */
export interface RoleSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  description?: T;
  permissions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user_select".
 */
export interface UserSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  email?: T;
  confirmToken?: T;
  confirmedAt?: T;
  password?: T;
  company?: T;
  role?: T;
  img?: T;
  tokens?: T;
  useTokens?: T;
  isConfirmed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  content?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specialist_select".
 */
export interface SpecialistSelect<T extends boolean = true> {
  user?: T;
  externalId?: T;
  title?: T;
  name?: T;
  top?: T;
  firstName?: T;
  lastName?: T;
  middleName?: T;
  birthDate?: T;
  experience?:
    | T
    | {
        name?: T;
        start?: T;
        end?: T;
        untilNow?: T;
        company?: T;
        position?: T;
        industry?: T;
        description?: T;
        aboutTeam?: T;
        achievements?: T;
        stack?: T;
        id?: T;
      };
  workFormat?: T;
  employmentType?: T;
  additionalEducations?:
    | T
    | {
        name?: T;
        year?: T;
        file?: T;
        id?: T;
      };
  educations?:
    | T
    | {
        name?: T;
        level?: T;
        major?: T;
        year?: T;
        id?: T;
      };
  salary?:
    | T
    | {
        amount?: T;
        currency?: T;
        hourlyRate?: T;
      };
  contacts?:
    | T
    | {
        phone?: T;
        email?: T;
        telegram?: T;
        other?: T;
      };
  language?:
    | T
    | {
        language?: T;
        level?: T;
        id?: T;
      };
  availableFrom?: T;
  employment?: T;
  relocation?: T;
  schedule?: T;
  hasVehicle?: T;
  driveExperience?: T;
  businessTripReadiness?: T;
  foreignProjectsReadiness?: T;
  age?: T;
  status?: T;
  citizenship?:
    | T
    | {
        name?: T;
        id?: T;
      };
  jobSearchStatus?: T;
  driverLicenseTypes?:
    | T
    | {
        type?: T;
        id?: T;
      };
  travelTime?: T;
  aboutMe?: T;
  gender?: T;
  img?: T;
  skills?: T;
  company?: T;
  grade?: T;
  specialization?: T;
  city?: T;
  country?: T;
  services?: T;
  visibility?: T;
  skillsExtracted?: T;
  formattedExperienceSkills?: T;
  dataSource?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specialization_select".
 */
export interface SpecializationSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "city_select".
 */
export interface CitySelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "country_select".
 */
export interface CountrySelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "businessArea_select".
 */
export interface BusinessAreaSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post_select".
 */
export interface PostSelect<T extends boolean = true> {
  image?: T;
  title?: T;
  description?: T;
  text?: T;
  text_html?: T;
  date?: T;
  author?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job_select".
 */
export interface JobSelect<T extends boolean = true> {
  name?: T;
  top?: T;
  externId?: T;
  requirements?:
    | T
    | {
        requirement?: T;
        mandatory?: T;
        id?: T;
      };
  tasks?:
    | T
    | {
        name?: T;
        id?: T;
      };
  description?: T;
  descriptionTeam?:
    | T
    | {
        name?: T;
        id?: T;
      };
  projectConditions?: T;
  industry?: T;
  specialization?: T;
  grades?: T;
  amount?: T;
  currency?: T;
  numberOfSpecialists?: T;
  attractionPeriod?:
    | T
    | {
        from?: T;
        to?: T;
        text?: T;
      };
  workFormat?: T;
  employmentType?: T;
  schedule?: T;
  workingHours?: T;
  projectStart?: T;
  city?: T;
  country?: T;
  language?:
    | T
    | {
        language?: T;
        level?: T;
        id?: T;
      };
  requiredCitizenship?:
    | T
    | {
        name?: T;
        id?: T;
      };
  status?: T;
  requiredSkills?: T;
  company?: T;
  dataSource?: T;
  parent?: T;
  visibility?: T;
  priority?: T;
  customer?: T;
  link?: T;
  searchQuery?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin_select".
 */
export interface AdminSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assistant_select".
 */
export interface AssistantSelect<T extends boolean = true> {
  name?: T;
  isDeleted?: T;
  user?: T;
  guestToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "message_select".
 */
export interface MessageSelect<T extends boolean = true> {
  content?: T;
  media?: T;
  assistant?: T;
  user?: T;
  status?: T;
  role?: T;
  inputTokens?: T;
  outputTokens?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industry_select".
 */
export interface IndustrySelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "language_select".
 */
export interface LanguageSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seed_select".
 */
export interface SeedSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "category_select".
 */
export interface CategorySelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "embedding_select".
 */
export interface EmbeddingSelect<T extends boolean = true> {
  query?: T;
  tableName?: T;
  embeddingId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dataSource_select".
 */
export interface DataSourceSelect<T extends boolean = true> {
  name?: T;
  href?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event_select".
 */
export interface EventSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  date?: T;
  startTime?: T;
  endTime?: T;
  calendarId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "log_select".
 */
export interface LogSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  data?: T;
  messageType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
