import type { Job } from './types';

export const mockJobs: Job[] = [
  {
    id: '1',
    title: 'Senior Full Stack Developer',
    company: 'TechFlow Inc.',
    location: 'San Francisco, CA',
    type: 'Full-time',
    salary: {
      min: 120000,
      max: 180000,
      currency: 'USD',
    },
    description: 'We are looking for a Senior Full Stack Developer to join our growing team. You will be responsible for developing and maintaining web applications using modern technologies.',
    requirements: [
      '5+ years of experience in full-stack development',
      'Strong proficiency in React and Node.js',
      'Experience with TypeScript and modern JavaScript',
      'Knowledge of cloud platforms (AWS, Azure, or GCP)',
      'Experience with database design and optimization',
    ],
    skills: ['React', 'Node.js', 'TypeScript', 'AWS', 'PostgreSQL'],
    experience: {
      min: 5,
      max: 10,
    },
    postedDate: '2025-01-10',
    applicationDeadline: '2025-02-15',
    applicants: 24,
    status: 'Open',
    benefits: ['Health Insurance', 'Dental Coverage', '401k Matching', 'Flexible PTO', 'Remote Work'],
    remote: true,
  },
  {
    id: '2',
    title: 'DevOps Engineer',
    company: 'CloudTech Solutions',
    location: 'Austin, TX',
    type: 'Full-time',
    salary: {
      min: 110000,
      max: 160000,
      currency: 'USD',
    },
    description: 'Join our DevOps team to help build and maintain scalable infrastructure. You will work with cutting-edge technologies to ensure our applications run smoothly.',
    requirements: [
      '3+ years of DevOps experience',
      'Strong knowledge of Docker and Kubernetes',
      'Experience with CI/CD pipelines',
      'Proficiency in Infrastructure as Code (Terraform)',
      'Knowledge of monitoring and logging tools',
    ],
    skills: ['Docker', 'Kubernetes', 'Terraform', 'Jenkins', 'AWS'],
    experience: {
      min: 3,
      max: 8,
    },
    postedDate: '2025-01-08',
    applicationDeadline: '2025-02-10',
    applicants: 18,
    status: 'Open',
    benefits: ['Health Insurance', 'Stock Options', 'Learning Budget', 'Gym Membership'],
    remote: false,
  },
  {
    id: '3',
    title: 'UX/UI Designer',
    company: 'Design Studio NYC',
    location: 'New York, NY',
    type: 'Full-time',
    salary: {
      min: 85000,
      max: 130000,
      currency: 'USD',
    },
    description: 'We are seeking a creative UX/UI Designer to join our design team. You will be responsible for creating intuitive and beautiful user experiences.',
    requirements: [
      '3+ years of UX/UI design experience',
      'Proficiency in Figma and Adobe Creative Suite',
      'Strong portfolio demonstrating design skills',
      'Experience with user research and testing',
      'Knowledge of design systems and accessibility',
    ],
    skills: ['Figma', 'Adobe Creative Suite', 'Prototyping', 'User Research', 'Design Systems'],
    experience: {
      min: 3,
      max: 7,
    },
    postedDate: '2025-01-12',
    applicationDeadline: '2025-02-20',
    applicants: 31,
    status: 'Open',
    benefits: ['Health Insurance', 'Creative Budget', 'Flexible Hours', 'Professional Development'],
    remote: true,
  },
  {
    id: '4',
    title: 'Data Scientist',
    company: 'Analytics Corp',
    location: 'Seattle, WA',
    type: 'Full-time',
    salary: {
      min: 130000,
      max: 190000,
      currency: 'USD',
    },
    description: 'Join our data science team to build machine learning models and extract insights from large datasets. You will work on exciting projects that drive business decisions.',
    requirements: [
      'PhD or Masters in Data Science, Statistics, or related field',
      '4+ years of experience in data science',
      'Strong programming skills in Python and R',
      'Experience with machine learning frameworks',
      'Knowledge of statistical analysis and modeling',
    ],
    skills: ['Python', 'Machine Learning', 'TensorFlow', 'SQL', 'Statistics'],
    experience: {
      min: 4,
      max: 10,
    },
    postedDate: '2025-01-05',
    applicationDeadline: '2025-02-05',
    applicants: 42,
    status: 'Open',
    benefits: ['Health Insurance', 'Stock Options', 'Research Budget', 'Conference Attendance'],
    remote: true,
  },
  {
    id: '5',
    title: 'Product Manager',
    company: 'ProductTech Inc.',
    location: 'Los Angeles, CA',
    type: 'Full-time',
    salary: {
      min: 140000,
      max: 200000,
      currency: 'USD',
    },
    description: 'We are looking for an experienced Product Manager to lead our product strategy and work closely with engineering and design teams.',
    requirements: [
      '5+ years of product management experience',
      'Strong analytical and problem-solving skills',
      'Experience with agile development methodologies',
      'Excellent communication and leadership skills',
      'Background in B2B SaaS products preferred',
    ],
    skills: ['Product Strategy', 'Agile', 'Analytics', 'User Research', 'Roadmapping'],
    experience: {
      min: 5,
      max: 12,
    },
    postedDate: '2025-01-07',
    applicationDeadline: '2025-02-12',
    applicants: 28,
    status: 'Open',
    benefits: ['Health Insurance', 'Equity Package', 'Unlimited PTO', 'Team Retreats'],
    remote: false,
  },
  {
    id: '6',
    title: 'Mobile Developer',
    company: 'Mobile Solutions LLC',
    location: 'Miami, FL',
    type: 'Contract',
    salary: {
      min: 80,
      max: 120,
      currency: 'USD',
    },
    description: 'Contract position for an experienced mobile developer to work on iOS and Android applications. 6-month contract with possibility of extension.',
    requirements: [
      '4+ years of mobile development experience',
      'Proficiency in React Native or Flutter',
      'Experience with native iOS and Android development',
      'Knowledge of mobile app deployment processes',
      'Strong problem-solving skills',
    ],
    skills: ['React Native', 'Swift', 'Kotlin', 'Flutter', 'iOS'],
    experience: {
      min: 4,
      max: 8,
    },
    postedDate: '2025-01-11',
    applicationDeadline: '2025-01-30',
    applicants: 15,
    status: 'Open',
    benefits: ['Hourly Rate', 'Flexible Schedule', 'Remote Work'],
    remote: true,
  },
  {
    id: '7',
    title: 'Frontend Developer',
    company: 'StartupXYZ',
    location: 'Remote',
    type: 'Full-time',
    salary: {
      min: 90000,
      max: 140000,
      currency: 'USD',
    },
    description: 'Join our startup as a Frontend Developer and help build the next generation of web applications. You will work in a fast-paced environment with modern technologies.',
    requirements: [
      '3+ years of frontend development experience',
      'Expert knowledge of React and modern JavaScript',
      'Experience with state management libraries',
      'Knowledge of responsive design and CSS frameworks',
      'Familiarity with testing frameworks',
    ],
    skills: ['React', 'JavaScript', 'TypeScript', 'CSS', 'Jest'],
    experience: {
      min: 3,
      max: 6,
    },
    postedDate: '2025-01-09',
    applicationDeadline: '2025-02-08',
    applicants: 37,
    status: 'Open',
    benefits: ['Equity Package', 'Health Insurance', 'Learning Budget', 'Flexible Hours'],
    remote: true,
  },
  {
    id: '8',
    title: 'Backend Engineer',
    company: 'Enterprise Solutions',
    location: 'Chicago, IL',
    type: 'Full-time',
    salary: {
      min: 115000,
      max: 165000,
      currency: 'USD',
    },
    description: 'We are seeking a Backend Engineer to join our enterprise team. You will be responsible for building scalable APIs and microservices.',
    requirements: [
      '4+ years of backend development experience',
      'Strong knowledge of Java or Python',
      'Experience with microservices architecture',
      'Knowledge of database design and optimization',
      'Familiarity with cloud platforms and containerization',
    ],
    skills: ['Java', 'Spring Boot', 'PostgreSQL', 'Docker', 'AWS'],
    experience: {
      min: 4,
      max: 9,
    },
    postedDate: '2025-01-06',
    applicationDeadline: '2025-02-06',
    applicants: 22,
    status: 'Open',
    benefits: ['Health Insurance', '401k Matching', 'Professional Development', 'Bonus Program'],
    remote: false,
  },
];